### ISSUE TITLE
add option to skip Keen6 copy protection

### ISSUE THREAD

**Issue by kajott** [sulix/omnispeak#12]
Would it be OK to remove the copy protection screen from episode 6? Sure, Omnispeak's premise is to be as true as possible to the original, and in this context, it absolutely makes sense to keep the copy protection screen intact, but still ... it's a major nuisance, and we left the "identical look and behavior" territory in favor of convenience already with the in-game graphics menu and extended joystick support.

It would be perfectly fine to make this a compile-time or command line option, and disabled by default, but as it is now, having to consult http://www.shikadi.net/keenwiki/Keen_6:_Aliens_Ate_My_Baby_Sitter!#Actors each time before playing is a little cumbersome :)

(I can do the changes myself and issue a PR if this topic is accepted.)

**Comment by sulix** [comment]
I've added a /NOCOPY option to skip the Creature question.
