### ISSUE TITLE
SDL2 render backend is drawing non-square pixels on my screen

### ISSUE THREAD

**Issue by owenmpierce** [sulix/omnispeak#13]
All commits after https://github.com/sulix/omnispeak/commit/05ecc8f4daee5f757f3ef3483d11e47c210d8b32 are drawing irregularly sized pixels.  A few rows are not drawn at the full width. [Example.](https://imgur.com/j5fkDdb).  (I've edited the image to highlight the problematic rows).  All commits before this have perfect square pixels.

System info:
Intel i5 3450
NVIDIA Gtx 750 ti 2gb
Driver version 390.116
Xubuntu Linux 18.04

When I compile https://github.com/sulix/omnispeak/commit/05ecc8f4daee5f757f3ef3483d11e47c210d8b32 using WITH_VULKAN=1, I get square pixels again.  However, in the latest commit, using any combination of WITH_OPENGL and WITH_VULKAN, and WITH_SDL2=1 gives me non-square pixels.

**Comment by sulix** [comment]
Thanks for reporting this (and finding the commit that broke it)!

It looks like I was calculating the size of the "integer" frambuffer without taking the overscan border into account. This should be fixed now (and probably works a little bit better than it did before, as we're handling the top and bottom border's 7-scanline heights better).
