### ISSUE TITLE
NOCOPY option not in README

### ISSUE THREAD

**Issue by Ryzee119** [sulix/omnispeak#23]
Very minor, but I noticed that the /NOCOPY command line arg used here is not documented in the readme https://github.com/sulix/omnispeak/blob/8bba1dc353632063c350078e34505ac6e6d3ba2f/src/ck_main.c#L711

**Comment by Ryzee119** [comment]
Same with `/NOAUDIOSYNC` 👍

**Comment by sulix** [comment]
Thanks! I've documented those options now.
