### ISSUE TITLE
Can't configure "Status" in Controller Configuration

### ISSUE THREAD

**Issue by rikimbo** [sulix/omnispeak#35]
I noticed that in the Controller Configuration, you can map Jump, Pogo and Fire, but you don't have an option to configure "Status". The quicksave/quickload options would be nice too.

**Comment by sulix** [comment]
I'll look into doing this. It's a little bit trickier than it looks, as the way we handle mapping the other buttons involves re-using some unused variables from the original game (and its config files), and so is limited to four buttons.

So, to do this properly, we'd want to:
- Move the config from the old CONFIG.CKx file to the new OMNISPK.CFG file, which is easily extended.
- Either extend ``ck_controlFrame`` to support more buttons, or find a non-controlFrame based way of passing button-presses through. The trick here might be tracking the previous state of the buttons, which isn't really done anywhere.

**Comment by sulix** [comment]
Started looking into this, and I have something which works in PR #37, but it needs more polish, and possibly a refactor, before I merge it. Feel free to give it a go in the meantime though if you want: but be warned that everything starts off bound to button 0 (and unlike before, the joystick config is now shared between episodes).

**Comment by rikimbo** [comment]
I gave it a try, and once I went through the configuration once, it works like a charm. Mapping the quick save/load functions to the shoulder buttons on a gamepad is really, really slick.

A single configuration shared between episodes is a really nice improvement. One thing surprised me, though: When loading another episode, I still had to select "Use <name of joystick>" before it would start using the controller. Once I did that, it loaded the shared configuration, but I just didn't expect that I'd have to do that when switching episodes.

**Comment by sulix** [comment]
Ah yes: that's a result of the original game working that way, and so having a place in its config file (CONFIG.CKx) to store the currently selected input device. The new config (OMNISPK.CFG) file is currently only used for options which are new to Omnispeak.

What I might do is add an extra config option to let Omnsipeak override the original Keen options with new config entries in OMNISPK.CFG.

In fact, I've updated PR #37 to do this for the control type by adding a new line to OMNISPK.CFG:
```
in_controlType = 2
```

It'll then update itself from then on when changed in-game. You can reset to the old behaviour by removing that line or setting it to -1.

This is probably not exactly how the final version will work, but seems okay so far.

**Comment by sulix** [comment]
Okay — after a few more minor changes, I'm going to call this fixed.

The joystick configuration is now stored in OMNISPK.CFG. The ``in_controlType`` variable can be set to make the overall input device also be shared between episodes, but it now should be set to "Keyboard1" or "Joystick1", rather than a number.

I'll no doubt do some more fixes to input settings saving/binding, but since "Status" (and QuickLoad, QuickSave) work, this is fixed by PR #37.
