### ISSUE TITLE
No high score entry after beating Keen 5

### ISSUE THREAD

**Issue by LoneFox78** [sulix/omnispeak#38]
After blowing up the QED, the high score list is shown, but the new score is not added to it.

The code for this exists, but is accidentally(?) left commented out:
https://github.com/sulix/omnispeak/blob/ac0b5a0b9ac8616258825c963e248371bdee2c7d/src/ck_game.c#L1019-L1021
Uncommenting it fixes the problem.

**Comment by sulix** [comment]
Thanks for finding this! I can confirm the issue and the fix, which I've pushed as commit bf6a45c.
