### ISSUE TITLE
Difference in new life trigger between originals and omnispeak

### ISSUE THREAD

**Issue by russhwolf** [sulix/omnispeak#57]
When l play the original games in DosBox (gog versions for 4/5, version 1.5 for Keen 6), getting the exact score required (ie exactly 20000, 40000, 80000, etc) triggers a new life to be granted immediately. In Omnispeak if you have the exact score, the new life isn't granted until the next time your score increases.

This is easiest to test in Keen 6 by collecting the pizzas at the top of the BWB level at the start of a new game, which total 20000 points for the first new life. Doing that in the original game triggers a new life, but in Omnispeak it doesn't until you collect some other points.

I'm guessing the fix is changing `>` to `>=` on [this line](https://github.com/sulix/omnispeak/blob/36f3e476be52daaed0d1cbe629b11b57075733c7/src/ck_keen.c#L197).

Aside: That function looks like it will also behave wrong if your score increased enough to trigger two new lives at once, but I don't know of any way for that to happen in practice (and so I have no idea what the behavior of the original games would be in that scenario).

**Comment by sulix** [comment]
Nice catch. I think you're right: the comparison in CK_IncreaseScore() should be ``>=``.
(Alongside the already existing demo mode check, as scores don't grant extra lives in demos for some reason.)

I think the original will have the same bug if you get enough points two lives at once, but again, I doubt that could happen. I think, best case, you'd >20000 pts in one frame, and I doubt there's any way you could get that.

I'm away right at the moment, so probably won't have a chance to fix this myself for another week or two, but if you want to fix it and send a PR or patch, I'd be happy to merge it.
