### ISSUE TITLE
OSI v1.04: Saved game incompatible with 16-bit DOS executable

### ISSUE THREAD

**Issue by NY00123** [sulix/omnispeak#60]
So, I'm not even sure if it's a discrepancy stemming just from a difference in the 16-bit DOS codebase (which is separate from Omnispeak's), or may point at something in Omnispeak as well; It could also be a side-effect of reduced available memory and/or a difference in the values of a certain pointer.

Either way, I've attached the saved game. It's compatible with OSI v1.04's 64-bit Linux binary, and may also load with the 32-bit DOS binary (as bundled with OSI v1.04). However, the 16-bit DOS one will report "Goplat moved to bad spot."

[SAVEGAM5.ZIP](https://github.com/user-attachments/files/16729596/SAVEGAM5.ZIP)

**Comment by sulix** [comment]
Thanks very much for the bug report!

The cause of this is a bit of Keen4-only code to zero out ``user2`` on platforms when they're loaded being left in by mistake (even though this is Keen5-based). Keen 5 uses ``user2`` to store how far between tiles a GoPlat is, so having it zeroed out desynchronises the actual location of a GoPlat from where it thinks it is.

A fixed version is available here: https://davidgow.net/stuff/osi-dos16-v0.91.zip
(I've tested your savegame against it, and it seems to work, but let me know if you hit any other problems.)

**Comment by NY00123** [comment]
Thanks for figuring it out! I confirm the bug as fixed. That'll probably be most related tests done for now. I've already completed the game with the 64-bit Linux executable, as written in the forums. I haven't found the Korath jail cell block. Question is if to retry looking for it at some point (especially without knowing the exact level) or taking a shortcut.

Having a short look at the modified function, it does look to me like a hybrid of Omnispeak and the reconstructed sources; I suppose it's as if Omnispeak had partially been backported to DOS16 using the reconstructed sources. One example is the generic object fields being named `user*` instead of `temp*.
